export const Permissions = {
  EMPLOYEE_READ: "EMPLOYEE_READ",
  EMPLOYEE_WRITE: "EMPLOYEE_WRITE",
  SALES_READ: "SALES_READ",
  SALES_WRITE: "SALES_WRITE",
  PURCHASE_READ: "PURCHASE_READ",
  PURCHASE_WRITE: "PURCHASE_WRITE",
  REPORT_READ: "REPORT_READ",
  
  // sales
  CUSTOMER_READ: "CUSTOMER_READ",
  CUSTOMER_WRITE: "CUSTOMER_WRITE",
  ITEM_READ: "ITEM_READ",
  ITEM_WRITE: "ITEM_WRITE",
  INVOICE_READ: "INVOICE_READ",
  INVOICE_WRITE: "INVOICE_WRITE",
  PAYMENT_READ: "PAYMENT_READ",
  PAYMENT_WRITE: "PAYMENT_WRITE",

  // purchasing
  SUPPLIER_READ: "SUPPLIER_READ",
  SUPPLIER_WRITE: "SUPPLIER_WRITE",
  PURCHASE_ORDER_READ: "PURCHASE_ORDER_READ",
  PURCHASE_ORDER_WRITE: "PURCHASE_ORDER_WRITE",

  // expenses
  EXPENSE_READ: "EXPENSE_READ",
  EXPENSE_WRITE: "EXPENSE_WRITE",
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
